### ISSUE TITLE
Request/Help classList regex

### ISSUE THREAD

**Issue by aquaductape** [paolotiu/tailwind-regex-list#5]
For some reason this regex doesn't work on classList property.
```js
{
  "tailwindCSS.experimental.classRegex": [
    "classList={{([^}]+)}}"
  ]
}
```

```js
<button
  class="p-2 border border-gray-200 rounded-md"
  classList={{ 'p-4': isDark() }}
>
  Lesson
</button>
```

Then I had a thought that you can't intellisense object string keys, but you can using the class comment hack. So it is possible to intellisense object string keys.
```js
```js
<button
  class="p-2 border border-gray-200 rounded-md"
  // class="
  classList={{ 'p-4': isDark() }}
  //"
>
  Lesson
</button>
```

But on paper the regex should work as it does here https://regex101.com/r/5I3Fsb/1

**Comment by carere** [comment]
Hello, I may found a solution, you can try this regex, it works for me :)
```json
{
  "tailwindCSS.experimental.classRegex": [
    ["classList={{([^;]*)}}", "\\s*?[\"'`]([^\"'`]*).*?:"]
  ]
}
```
Hope it helps ;)

@paolotiu You may add it to the list of the readme :)

**Comment by paolotiu** [comment]
Thanks for this @carere! I'll verify then add it to the README.

**Comment by carere** [comment]
@paolotiu  Hello, i was wrong in my previous regex, the good one is this one:
```json
{
  "tailwindCSS.experimental.classRegex": [
    ["classList={{([^;]*)}}", "\\s*?[\"'`]([^\"'`]*).:"]
  ],
}
```
You can [test it here](https://regex101.com/r/xdfIhY/1)

**Comment by paolotiu** [comment]
Added it! Thank you so much @carere  and @aquaductape <3
