### ISSUE TITLE
clsx example does not behave correctly

### ISSUE THREAD

**Issue by bstro** [paolotiu/tailwind-regex-list#8]
great resource! thanks for providing this. running into an issue with the clsx example:

given this config:
```"tailwindCSS.experimental.classRegex": ["clsx\\(([^)]*)\\)", "(?:'|\"|`)([^']*)(?:'|\"|`)"]```
intellisense only works outside of a string:

i.e. this works, but is not useful:
<img width="502" alt="image" src="https://user-images.githubusercontent.com/627290/226999753-61ebec5d-da79-4a84-84bb-5c5868cfb5c5.png">

whereas this should work, but does not:
<img width="546" alt="image" src="https://user-images.githubusercontent.com/627290/226999854-7cf7727a-59e6-4442-8c6d-9db0e3f781d3.png">

using tailwind 3.2.7

**Comment by paolotiu** [comment]
Thanks for this! I'll look into it then get back to you.

**Comment by paolotiu** [comment]
Oh I think I see whats wrong. the config should be enclosed with an array. Something like this:

```json
"tailwindCSS.experimental.classRegex": [
["clsx\\(([^)]*)\\)", "(?:'|\"|`)([^']*)(?:'|\"|`)"]
]
```

I do think that the examples don't make that clear enough. I will fix this. Thanks for bringing it up 😄

**Comment by paolotiu** [comment]
My bad! I see the problem in the regex. 

This should work:

```json
"tailwindCSS.experimental.classRegex": [
    ["clsx\\(([^)]*)\\)", "(?:'|\"|`)([^\"'`]*)(?:'|\"|`)"]
 ]
```

The original snippet only worked for when using single quotes. This change should fix it. Let me know if theres still something wrong,

**Comment by bstro** [comment]
This seems to work well! Thanks a lot @paolotiu

**Comment by paolotiu** [comment]
Great to hear that 😄
